branches:
  only:
    - master

skip_tags: true

version: "{build}"

assembly_info:
  patch: false

platform:
  - Any CPU

configuration:
  - Release

before_build:
  - cmd: nuget restore

build:
  project: Zoltu.Linq.NotNull.sln
  verbosity: minimal

artifacts:
  - path: Zoltu.Linq.NotNull/bin/**/*.nupkg
  - path: Zoltu.Linq.NotNull/bin/**/*.dll
  - path: Zoltu.Linq.NotNull/bin/**/*.pdb

deploy:
  provider: NuGet
  api_key:
    secure: X6YnwwH05dy0122NypnAz4w1ti39JQ49I8bQqDsLHzUwAp1rhvm6yvPo03EpwD8e

